-- Script seguro para recrear todas las tablas, secuencias y objetos.
-- Ordenado para evitar ORA-00942 y ORA-00955.

PROMPT Limpieza de objetos (triggers, paquetes, tipos, tablas, secuencias)...
DECLARE
    PROCEDURE safe_drop(p_sql VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE NOT IN (-4043, -4044, -4045, -4080, -2289, -942, -21700, -21701, -2303, -2304) THEN
                RAISE;
            END IF;
    END;
BEGIN
    -- Triggers de negocio / PK
    safe_drop('DROP TRIGGER TRG_VALIDA_STOCK_VENTA');
    safe_drop('DROP TRIGGER TRG_HAB_OCUPADA_ON_DETALLE');
    safe_drop('DROP TRIGGER TRG_HAB_LIBRE_ON_DETALLE_DEL');
    safe_drop('DROP TRIGGER TRG_PK_USUARIO');
    safe_drop('DROP TRIGGER TRG_MISMA_PK_USUARIO');
    safe_drop('DROP TRIGGER TRG_PK_EMPLEADO');
    safe_drop('DROP TRIGGER TRG_MISMA_PK_EMPLEADO');
    safe_drop('DROP TRIGGER TRG_PK_CLIENTE');
    safe_drop('DROP TRIGGER TRG_PK_PRODUCTO');
    safe_drop('DROP TRIGGER TRG_MISMA_PK_PRODUCTO');
    safe_drop('DROP TRIGGER TRG_PK_ROL');
    safe_drop('DROP TRIGGER TRG_PK_PEDIDO');
    safe_drop('DROP TRIGGER TRG_PK_MOVIMIENTO_STOCK');
    safe_drop('DROP TRIGGER TRG_PK_PAGO_VENTA');
    safe_drop('DROP TRIGGER TRG_PK_VENTA');
    safe_drop('DROP TRIGGER TRG_PK_PAGO_HAB');
    safe_drop('DROP TRIGGER TRG_PK_SOLICITUD_ADMIN');

    -- Paquetes
    safe_drop('DROP PACKAGE BODY PKG_REPORTES');
    safe_drop('DROP PACKAGE PKG_REPORTES');
    safe_drop('DROP PACKAGE BODY PKG_PEDIDO');
    safe_drop('DROP PACKAGE PKG_PEDIDO');

    -- Procedimientos y funciones
    safe_drop('DROP PROCEDURE JRGY_PRO_RECALC_STOCK');
    safe_drop('DROP PROCEDURE JRGY_PRO_PAGO_HABITACION');
    safe_drop('DROP PROCEDURE JRGY_PRO_REGISTRAR_PEDIDO');
    safe_drop('DROP PROCEDURE JRGY_PRO_REGISTRAR_VENTA');
    safe_drop('DROP PROCEDURE JRGY_PRO_ASIGNAR_ROL');
    safe_drop('DROP PROCEDURE JRGY_PRO_DELETE_PEDIDO');
    safe_drop('DROP PROCEDURE JRGY_PRO_UPDATE_PEDIDO_TOTAL');
    safe_drop('DROP PROCEDURE JRGY_PRO_INSERT_PEDIDO');
    safe_drop('DROP PROCEDURE JRGY_PRO_LOGIN');
    safe_drop('DROP PROCEDURE CRUD_DETALLE_VENTA');
    safe_drop('DROP PROCEDURE CRUD_VENTA');
    safe_drop('DROP PROCEDURE CRUD_DETALLE_PEDIDO');
    safe_drop('DROP PROCEDURE CRUD_PEDIDO');
    safe_drop('DROP PROCEDURE CRUD_DETALLE_PAGO_HABITACION');
    safe_drop('DROP PROCEDURE CRUD_PAGO_HABITACION');
    safe_drop('DROP PROCEDURE CRUD_HABITACION');
    safe_drop('DROP PROCEDURE CRUD_PROVEEDOR');
    safe_drop('DROP PROCEDURE CRUD_CALLE');
    safe_drop('DROP PROCEDURE CRUD_COMUNA');
    safe_drop('DROP PROCEDURE CRUD_CIUDAD');
    safe_drop('DROP PROCEDURE CRUD_REGION');
    safe_drop('DROP PROCEDURE CRUD_USUARIO_ROL');
    safe_drop('DROP PROCEDURE CRUD_ROL');
    safe_drop('DROP PROCEDURE CRUD_EMPLEADO');
    safe_drop('DROP PROCEDURE CRUD_PRODUCTO');
    safe_drop('DROP PROCEDURE CRUD_USUARIO');
    safe_drop('DROP PROCEDURE CRUD_PAGO_VENTA');
    safe_drop('DROP PROCEDURE CRUD_MOVIMIENTO_STOCK');

    safe_drop('DROP FUNCTION FN_CALC_IVA');
    safe_drop('DROP FUNCTION FN_CALC_COMISION');
    safe_drop('DROP FUNCTION FN_STOCK_DISP');

    -- Tipos
    safe_drop('DROP TYPE DETALLE_PEDIDO_TAB');
    safe_drop('DROP TYPE DETALLE_PEDIDO_REC');
    safe_drop('DROP TYPE DETALLE_VENTA_TAB');
    safe_drop('DROP TYPE DETALLE_VENTA_REC');
    safe_drop('DROP TYPE DETALLE_ESTADIA_TAB');
    safe_drop('DROP TYPE DETALLE_ESTADIA_REC');

    -- Tablas (en orden descendente de dependencia)
    safe_drop('DROP TABLE JRGY_DETALLE_PAGO_HABITACION CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_DETALLE_PEDIDO CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_DETALLE_VENTA CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_MOVIMIENTO_STOCK CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_PAGO_VENTA CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_PAGO_HABITACION CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_PEDIDO CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_VENTA CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_HABITACION CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_USUARIO_ROL CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_SOLICITUD_ADMIN CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_EMPLEADO CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_CLIENTE CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_PRODUCTO CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_PROVEEDOR CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_CALLE CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_COMUNA CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_CIUDAD CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_REGION CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_DEPARTAMENTO CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_USUARIO CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_ROL CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_CAT_ESTADO_USUARIO CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_CAT_ESTADO_LABORAL CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_CAT_ESTADO_HABITACION CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_CAT_TIPO_HABITACION CASCADE CONSTRAINTS');
    safe_drop('DROP TABLE JRGY_CAT_MODO_PAGO CASCADE CONSTRAINTS');

    -- Secuencias
    safe_drop('DROP SEQUENCE SQ_PK_USUARIO');
    safe_drop('DROP SEQUENCE SQ_PK_EMPLEADO');
    safe_drop('DROP SEQUENCE SQ_PK_CLIENTE');
    safe_drop('DROP SEQUENCE SQ_PK_PRODUCTO');
    safe_drop('DROP SEQUENCE SQ_PK_PEDIDO');
    safe_drop('DROP SEQUENCE SQ_PK_ROL');
    safe_drop('DROP SEQUENCE SQ_PK_MOVIMIENTO_STOCK');
    safe_drop('DROP SEQUENCE SQ_PK_PAGO_VENTA');
    safe_drop('DROP SEQUENCE SQ_PK_VENTA');
    safe_drop('DROP SEQUENCE SQ_PK_PAGO_HAB');
    safe_drop('DROP SEQUENCE SQ_PK_SOLICITUD_ADMIN');
END;
/

PROMPT Creacion de tablas catalogo...
-- 1) Catalogos y dominios
CREATE TABLE JRGY_CAT_ESTADO_USUARIO (
    COD_ESTADO_USUARIO NUMBER,
    ESTADO_USUARIO VARCHAR2(30),
    CONSTRAINT PK_JRGY_CAT_ESTADO_USUARIO PRIMARY KEY (COD_ESTADO_USUARIO)
);

CREATE TABLE JRGY_CAT_ESTADO_LABORAL (
    COD_ESTADO_LABORAL NUMBER,
    ESTADO_LABORAL VARCHAR2(30),
    CONSTRAINT PK_JRGY_CAT_ESTADO_LABORAL PRIMARY KEY (COD_ESTADO_LABORAL)
);

CREATE TABLE JRGY_CAT_ESTADO_HABITACION (
    COD_ESTADO_HABITACION NUMBER,
    ESTADO_HABITACION VARCHAR2(30),
    CONSTRAINT PK_JRGY_CAT_ESTADO_HABITACION PRIMARY KEY (COD_ESTADO_HABITACION)
);

CREATE TABLE JRGY_CAT_TIPO_HABITACION (
    COD_TIPO_HABITACION NUMBER,
    TIPO_HABITACION VARCHAR2(50),
    CONSTRAINT PK_JRGY_CAT_TIPO_HABITACION PRIMARY KEY (COD_TIPO_HABITACION)
);

CREATE TABLE JRGY_CAT_MODO_PAGO (
    COD_MODO_PAGO NUMBER,
    MODO_PAGO VARCHAR2(30),
    CONSTRAINT PK_JRGY_CAT_MODO_PAGO PRIMARY KEY (COD_MODO_PAGO)
);

CREATE TABLE JRGY_REGION (
    COD_REGION NUMBER,
    REGION VARCHAR2(50),
    CONSTRAINT PK_JRGY_REGION PRIMARY KEY (COD_REGION)
);

CREATE TABLE JRGY_CIUDAD (
    COD_CIUDAD NUMBER,
    CIUDAD VARCHAR2(50),
    COD_REGION NUMBER,
    CONSTRAINT PK_JRGY_CIUDAD PRIMARY KEY (COD_CIUDAD),
    CONSTRAINT FK_JRGY_CIUDAD_REGION FOREIGN KEY (COD_REGION) REFERENCES JRGY_REGION (COD_REGION)
);

CREATE TABLE JRGY_COMUNA (
    COD_COMUNA NUMBER,
    COMUNA VARCHAR2(50),
    COD_CIUDAD NUMBER,
    CONSTRAINT PK_JRGY_COMUNA PRIMARY KEY (COD_COMUNA),
    CONSTRAINT FK_JRGY_COMUNA_CIUDAD FOREIGN KEY (COD_CIUDAD) REFERENCES JRGY_CIUDAD (COD_CIUDAD)
);

CREATE TABLE JRGY_CALLE (
    COD_CALLE NUMBER,
    CALLE VARCHAR2(50),
    NRO NUMBER,
    COD_COMUNA NUMBER,
    CONSTRAINT PK_JRGY_CALLE PRIMARY KEY (COD_CALLE),
    CONSTRAINT FK_JRGY_CALLE_COMUNA FOREIGN KEY (COD_COMUNA) REFERENCES JRGY_COMUNA (COD_COMUNA)
);

CREATE TABLE JRGY_ROL (
    COD_ROL NUMBER,
    NOMBRE_ROL VARCHAR2(50),
    CONSTRAINT PK_JRGY_ROL PRIMARY KEY (COD_ROL)
);

PROMPT Creacion de tablas base...
-- 2) Tablas base
CREATE TABLE JRGY_USUARIO (
    COD_USUARIO NUMBER,
    NOMBRE_USUARIO VARCHAR2(50),
    APELLIDO1_USUARIO VARCHAR2(50),
    APELLIDO2_USUARIO VARCHAR2(50),
    EMAIL_USUARIO VARCHAR2(100),
    TELEFONO_USUARIO NUMBER,
    CONTRASENA_HASH VARCHAR2(255),
    COD_ESTADO_USUARIO NUMBER,
    CONSTRAINT PK_JRGY_USUARIO PRIMARY KEY (COD_USUARIO),
    CONSTRAINT FK_JRGY_USUARIO_ESTADO FOREIGN KEY (COD_ESTADO_USUARIO) REFERENCES JRGY_CAT_ESTADO_USUARIO (COD_ESTADO_USUARIO)
);

CREATE TABLE JRGY_DEPARTAMENTO (
    COD_DEPARTAMENTO NUMBER,
    NOMBRE_DEPARTAMENTO VARCHAR2(50),
    JEFE_EMPLEADO_ID NUMBER,
    CONSTRAINT PK_JRGY_DEPARTAMENTO PRIMARY KEY (COD_DEPARTAMENTO)
);

CREATE TABLE JRGY_CLIENTE (
    COD_CLIENTE NUMBER,
    COD_USUARIO NUMBER,
    FECHA_ALTA DATE,
    CONSTRAINT PK_JRGY_CLIENTE PRIMARY KEY (COD_CLIENTE),
    CONSTRAINT FK_JRGY_CLIENTE_USUARIO FOREIGN KEY (COD_USUARIO) REFERENCES JRGY_USUARIO (COD_USUARIO)
);

CREATE TABLE JRGY_PROVEEDOR (
    COD_PROVEEDOR NUMBER,
    NOMBRE_PROVEEDOR VARCHAR2(50),
    DIRECCION_PROVEEDOR VARCHAR2(100),
    TELEFONO_PROVEEDOR NUMBER,
    COD_REGION NUMBER,
    CONSTRAINT PK_JRGY_PROVEEDOR PRIMARY KEY (COD_PROVEEDOR),
    CONSTRAINT FK_JRGY_PROVEEDOR_REGION FOREIGN KEY (COD_REGION) REFERENCES JRGY_REGION (COD_REGION)
);

CREATE TABLE JRGY_PRODUCTO (
    COD_PRODUCTO NUMBER,
    NOMBRE_PRODUCTO VARCHAR2(50),
    TIPO_PRODUCTO VARCHAR2(20),
    PRECIO_PRODUCTO NUMBER,
    CANTIDAD_PRODUCTO NUMBER,
    STOCK_PRODUCTO NUMBER,
    CONSTRAINT PK_JRGY_PRODUCTO PRIMARY KEY (COD_PRODUCTO)
);

CREATE TABLE JRGY_EMPLEADO (
    COD_EMPLEADO NUMBER,
    COD_USUARIO NUMBER,
    COD_DEPARTAMENTO NUMBER,
    CARGO VARCHAR2(50),
    FECHA_CONTRATACION DATE,
    SALARIO NUMBER,
    COMISION NUMBER,
    COD_ESTADO_LABORAL NUMBER,
    CONSTRAINT PK_JRGY_EMPLEADO PRIMARY KEY (COD_EMPLEADO),
    CONSTRAINT FK_JRGY_EMPLEADO_USUARIO FOREIGN KEY (COD_USUARIO) REFERENCES JRGY_USUARIO (COD_USUARIO),
    CONSTRAINT FK_JRGY_EMPLEADO_DEPTO FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES JRGY_DEPARTAMENTO (COD_DEPARTAMENTO),
    CONSTRAINT FK_JRGY_EMPLEADO_ESTADO FOREIGN KEY (COD_ESTADO_LABORAL) REFERENCES JRGY_CAT_ESTADO_LABORAL (COD_ESTADO_LABORAL)
);

ALTER TABLE JRGY_DEPARTAMENTO
    ADD CONSTRAINT FK_JRGY_DEPTO_JEFE FOREIGN KEY (JEFE_EMPLEADO_ID) REFERENCES JRGY_EMPLEADO (COD_EMPLEADO);

PROMPT Creacion de tablas dependientes...
-- 3) Tablas dependientes
CREATE TABLE JRGY_USUARIO_ROL (
    COD_USUARIO NUMBER,
    COD_ROL NUMBER,
    CONSTRAINT PK_JRGY_USUARIO_ROL PRIMARY KEY (COD_USUARIO, COD_ROL),
    CONSTRAINT FK_JRGY_USUARIO_ROL_USUARIO FOREIGN KEY (COD_USUARIO) REFERENCES JRGY_USUARIO (COD_USUARIO),
    CONSTRAINT FK_JRGY_USUARIO_ROL_ROL FOREIGN KEY (COD_ROL) REFERENCES JRGY_ROL (COD_ROL)
);

CREATE TABLE JRGY_SOLICITUD_ADMIN (
    COD_SOLICITUD NUMBER,
    COD_USUARIO NUMBER NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL,
    MOTIVO VARCHAR2(255),
    APROBADO_POR NUMBER,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_RESOLUCION DATE,
    CONSTRAINT PK_JRGY_SOLICITUD_ADMIN PRIMARY KEY (COD_SOLICITUD),
    CONSTRAINT FK_JRGY_SOLICITUD_USUARIO FOREIGN KEY (COD_USUARIO) REFERENCES JRGY_USUARIO (COD_USUARIO),
    CONSTRAINT FK_JRGY_SOLICITUD_APROBADO FOREIGN KEY (APROBADO_POR) REFERENCES JRGY_USUARIO (COD_USUARIO),
    CONSTRAINT CHK_JRGY_SOLICITUD_ESTADO CHECK (ESTADO IN ('pending', 'approved', 'rejected'))
);

CREATE INDEX IDX_JRGY_SOLICITUD_USUARIO ON JRGY_SOLICITUD_ADMIN (COD_USUARIO);

CREATE TABLE JRGY_HABITACION (
    COD_HABITACION NUMBER,
    NRO_HABITACION NUMBER,
    CAPACIDAD NUMBER,
    COD_TIPO_HABITACION NUMBER,
    COD_ESTADO_HABITACION NUMBER,
    PRECIO_BASE NUMBER,
    CONSTRAINT PK_JRGY_HABITACION PRIMARY KEY (COD_HABITACION),
    CONSTRAINT FK_JRGY_HAB_TIPO FOREIGN KEY (COD_TIPO_HABITACION) REFERENCES JRGY_CAT_TIPO_HABITACION (COD_TIPO_HABITACION),
    CONSTRAINT FK_JRGY_HAB_ESTADO FOREIGN KEY (COD_ESTADO_HABITACION) REFERENCES JRGY_CAT_ESTADO_HABITACION (COD_ESTADO_HABITACION)
);

CREATE TABLE JRGY_PAGO_HABITACION (
    COD_PAGO_HABITACION NUMBER,
    FECHA_PAGO DATE,
    VALOR_TOTAL_PAGO NUMBER,
    COD_USUARIO NUMBER,
    CONSTRAINT PK_JRGY_PAGO_HABITACION PRIMARY KEY (COD_PAGO_HABITACION),
    CONSTRAINT FK_JRGY_PAGO_HABITACION_USUARIO FOREIGN KEY (COD_USUARIO) REFERENCES JRGY_USUARIO (COD_USUARIO)
);

CREATE TABLE JRGY_DETALLE_PAGO_HABITACION (
    COD_PAGO_HABITACION NUMBER,
    COD_HABITACION NUMBER,
    FECHA_ESTADIA DATE,
    PRECIO_HABITACION NUMBER,
    DIAS NUMBER,
    CONSTRAINT PK_JRGY_DETALLE_PAGO_HABITACION PRIMARY KEY (COD_PAGO_HABITACION, COD_HABITACION),
    CONSTRAINT FK_JRGY_DETALLE_PAGO_HABITACION_PAGO FOREIGN KEY (COD_PAGO_HABITACION) REFERENCES JRGY_PAGO_HABITACION (COD_PAGO_HABITACION) ON DELETE CASCADE,
    CONSTRAINT FK_JRGY_DETALLE_PAGO_HABITACION_HAB FOREIGN KEY (COD_HABITACION) REFERENCES JRGY_HABITACION (COD_HABITACION)
);

CREATE TABLE JRGY_PEDIDO (
    COD_PEDIDO NUMBER,
    VALOR_TOTAL NUMBER,
    FECHA_PEDIDO DATE,
    COD_EMPLEADO NUMBER,
    CONSTRAINT PK_JRGY_PEDIDO PRIMARY KEY (COD_PEDIDO),
    CONSTRAINT FK_JRGY_PEDIDO_EMPLEADO FOREIGN KEY (COD_EMPLEADO) REFERENCES JRGY_EMPLEADO (COD_EMPLEADO)
);

CREATE TABLE JRGY_DETALLE_PEDIDO (
    COD_PEDIDO NUMBER,
    COD_PROVEEDOR NUMBER,
    COD_PRODUCTO NUMBER,
    NOMBRE_PRODUCTO VARCHAR2(50),
    CANTIDAD_PRODUCTO NUMBER,
    PRECIO_COMPRA NUMBER,
    PRECIO_TOTAL NUMBER,
    CONSTRAINT PK_JRGY_DETALLE_PEDIDO PRIMARY KEY (COD_PEDIDO, COD_PROVEEDOR, COD_PRODUCTO),
    CONSTRAINT FK_JRGY_DETALLE_PEDIDO_PEDIDO FOREIGN KEY (COD_PEDIDO) REFERENCES JRGY_PEDIDO (COD_PEDIDO) ON DELETE CASCADE,
    CONSTRAINT FK_JRGY_DETALLE_PEDIDO_PROVEEDOR FOREIGN KEY (COD_PROVEEDOR) REFERENCES JRGY_PROVEEDOR (COD_PROVEEDOR),
    CONSTRAINT FK_JRGY_DETALLE_PEDIDO_PRODUCTO FOREIGN KEY (COD_PRODUCTO) REFERENCES JRGY_PRODUCTO (COD_PRODUCTO)
);

CREATE TABLE JRGY_VENTA (
    COD_VENTA NUMBER,
    COD_USUARIO NUMBER,
    COD_EMPLEADO NUMBER,
    FECHA_VENTA DATE,
    CONSTRAINT PK_JRGY_VENTA PRIMARY KEY (COD_VENTA),
    CONSTRAINT FK_JRGY_VENTA_USUARIO FOREIGN KEY (COD_USUARIO) REFERENCES JRGY_USUARIO (COD_USUARIO),
    CONSTRAINT FK_JRGY_VENTA_EMPLEADO FOREIGN KEY (COD_EMPLEADO) REFERENCES JRGY_EMPLEADO (COD_EMPLEADO)
);

CREATE TABLE JRGY_DETALLE_VENTA (
    COD_VENTA NUMBER,
    COD_PRODUCTO NUMBER,
    CANTIDAD NUMBER,
    PRECIO_PRODUCTO NUMBER,
    PRECIO_TOTAL NUMBER,
    CONSTRAINT PK_JRGY_DETALLE_VENTA PRIMARY KEY (COD_VENTA, COD_PRODUCTO),
    CONSTRAINT FK_JRGY_DETALLE_VENTA_VENTA FOREIGN KEY (COD_VENTA) REFERENCES JRGY_VENTA (COD_VENTA) ON DELETE CASCADE,
    CONSTRAINT FK_JRGY_DETALLE_VENTA_PRODUCTO FOREIGN KEY (COD_PRODUCTO) REFERENCES JRGY_PRODUCTO (COD_PRODUCTO)
);

CREATE TABLE JRGY_MOVIMIENTO_STOCK (
    COD_MOVIMIENTO NUMBER,
    COD_PRODUCTO NUMBER,
    TIPO_MOVIMIENTO VARCHAR2(20),
    CANTIDAD NUMBER,
    FECHA_MOVIMIENTO DATE,
    MOTIVO VARCHAR2(100),
    CONSTRAINT PK_JRGY_MOVIMIENTO_STOCK PRIMARY KEY (COD_MOVIMIENTO),
    CONSTRAINT FK_JRGY_MOVIMIENTO_STOCK_PRODUCTO FOREIGN KEY (COD_PRODUCTO) REFERENCES JRGY_PRODUCTO (COD_PRODUCTO)
);

CREATE TABLE JRGY_PAGO_VENTA (
    COD_PAGO NUMBER,
    COD_VENTA NUMBER,
    COD_MODO_PAGO NUMBER,
    MONTO NUMBER,
    FECHA_PAGO DATE,
    CONSTRAINT PK_JRGY_PAGO_VENTA PRIMARY KEY (COD_PAGO),
    CONSTRAINT FK_JRGY_PAGO_VENTA_VENTA FOREIGN KEY (COD_VENTA) REFERENCES JRGY_VENTA (COD_VENTA),
    CONSTRAINT FK_JRGY_PAGO_VENTA_MODO FOREIGN KEY (COD_MODO_PAGO) REFERENCES JRGY_CAT_MODO_PAGO (COD_MODO_PAGO)
);

PROMPT Creacion de secuencias y triggers PK...
-- 4) Secuencias y triggers para PK
CREATE SEQUENCE SQ_PK_USUARIO START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PK_USUARIO BEFORE INSERT ON JRGY_USUARIO FOR EACH ROW
BEGIN
    IF :NEW.COD_USUARIO IS NULL THEN
        SELECT SQ_PK_USUARIO.NEXTVAL INTO :NEW.COD_USUARIO FROM DUAL;
    END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_MISMA_PK_USUARIO BEFORE INSERT ON JRGY_USUARIO FOR EACH ROW
DECLARE V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM JRGY_USUARIO WHERE COD_USUARIO = :NEW.COD_USUARIO;
    IF V_COUNT > 0 THEN RAISE_APPLICATION_ERROR(-2001, 'YA EXISTE EL USUARIO'); END IF;
END;
/

CREATE SEQUENCE SQ_PK_CLIENTE START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PK_CLIENTE BEFORE INSERT ON JRGY_CLIENTE FOR EACH ROW
BEGIN IF :NEW.COD_CLIENTE IS NULL THEN :NEW.COD_CLIENTE := SQ_PK_CLIENTE.NEXTVAL; END IF; END;
/

CREATE SEQUENCE SQ_PK_EMPLEADO START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PK_EMPLEADO BEFORE INSERT ON JRGY_EMPLEADO FOR EACH ROW
BEGIN IF :NEW.COD_EMPLEADO IS NULL THEN :NEW.COD_EMPLEADO := SQ_PK_EMPLEADO.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_MISMA_PK_EMPLEADO BEFORE INSERT ON JRGY_EMPLEADO FOR EACH ROW
DECLARE V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM JRGY_EMPLEADO WHERE COD_EMPLEADO = :NEW.COD_EMPLEADO;
    IF V_COUNT > 0 THEN RAISE_APPLICATION_ERROR(-2002, 'YA EXISTE EL EMPLEADO'); END IF;
END;
/

CREATE SEQUENCE SQ_PK_PRODUCTO START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PK_PRODUCTO BEFORE INSERT ON JRGY_PRODUCTO FOR EACH ROW
BEGIN IF :NEW.COD_PRODUCTO IS NULL THEN :NEW.COD_PRODUCTO := SQ_PK_PRODUCTO.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_MISMA_PK_PRODUCTO BEFORE INSERT ON JRGY_PRODUCTO FOR EACH ROW
DECLARE V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM JRGY_PRODUCTO WHERE COD_PRODUCTO = :NEW.COD_PRODUCTO;
    IF V_COUNT > 0 THEN RAISE_APPLICATION_ERROR(-2003, 'YA EXISTE EL PRODUCTO'); END IF;
END;
/

CREATE SEQUENCE SQ_PK_PEDIDO START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE SEQUENCE SQ_PK_ROL START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PK_ROL BEFORE INSERT ON JRGY_ROL FOR EACH ROW
BEGIN IF :NEW.COD_ROL IS NULL THEN :NEW.COD_ROL := SQ_PK_ROL.NEXTVAL; END IF; END;
/

CREATE SEQUENCE SQ_PK_SOLICITUD_ADMIN START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PK_SOLICITUD_ADMIN BEFORE INSERT ON JRGY_SOLICITUD_ADMIN FOR EACH ROW
BEGIN IF :NEW.COD_SOLICITUD IS NULL THEN :NEW.COD_SOLICITUD := SQ_PK_SOLICITUD_ADMIN.NEXTVAL; END IF; END;
/

CREATE SEQUENCE SQ_PK_MOVIMIENTO_STOCK START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PK_MOVIMIENTO_STOCK BEFORE INSERT ON JRGY_MOVIMIENTO_STOCK FOR EACH ROW
BEGIN IF :NEW.COD_MOVIMIENTO IS NULL THEN :NEW.COD_MOVIMIENTO := SQ_PK_MOVIMIENTO_STOCK.NEXTVAL; END IF; END;
/

CREATE SEQUENCE SQ_PK_PAGO_VENTA START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PK_PAGO_VENTA BEFORE INSERT ON JRGY_PAGO_VENTA FOR EACH ROW
BEGIN IF :NEW.COD_PAGO IS NULL THEN :NEW.COD_PAGO := SQ_PK_PAGO_VENTA.NEXTVAL; END IF; END;
/

CREATE SEQUENCE SQ_PK_VENTA START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PK_VENTA BEFORE INSERT ON JRGY_VENTA FOR EACH ROW
BEGIN IF :NEW.COD_VENTA IS NULL THEN :NEW.COD_VENTA := SQ_PK_VENTA.NEXTVAL; END IF; END;
/

CREATE SEQUENCE SQ_PK_PAGO_HAB START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_PK_PAGO_HAB BEFORE INSERT ON JRGY_PAGO_HABITACION FOR EACH ROW
BEGIN IF :NEW.COD_PAGO_HABITACION IS NULL THEN :NEW.COD_PAGO_HABITACION := SQ_PK_PAGO_HAB.NEXTVAL; END IF; END;
/

PROMPT Creacion de tipos...
-- 5) Tipos
CREATE OR REPLACE TYPE DETALLE_PEDIDO_REC AS OBJECT (
    COD_PROVEEDOR NUMBER,
    COD_PRODUCTO NUMBER,
    NOMBRE_PRODUCTO VARCHAR2(50),
    CANTIDAD_PRODUCTO NUMBER,
    PRECIO_COMPRA NUMBER
);
/
CREATE OR REPLACE TYPE DETALLE_PEDIDO_TAB AS TABLE OF DETALLE_PEDIDO_REC;
/
CREATE OR REPLACE TYPE DETALLE_VENTA_REC AS OBJECT (
    COD_PRODUCTO NUMBER,
    CANTIDAD NUMBER,
    PRECIO_PRODUCTO NUMBER
);
/
CREATE OR REPLACE TYPE DETALLE_VENTA_TAB AS TABLE OF DETALLE_VENTA_REC;
/
CREATE OR REPLACE TYPE DETALLE_ESTADIA_REC AS OBJECT (
    COD_HABITACION NUMBER,
    FECHA_ESTADIA DATE,
    DIAS NUMBER,
    PRECIO_HABITACION NUMBER
);
/
CREATE OR REPLACE TYPE DETALLE_ESTADIA_TAB AS TABLE OF DETALLE_ESTADIA_REC;
/

PROMPT Creacion de procedimientos / funciones / paquetes...
-- 6) Procedimientos / Funciones / Paquetes
-- CRUD usuario
CREATE OR REPLACE PROCEDURE CRUD_USUARIO(
    OPCION_P IN VARCHAR2,
    COD_USUARIO_P IN NUMBER,
    NOMBRE_USUARIO_P IN VARCHAR2,
    APELLIDO1_USUARIO_P IN VARCHAR2,
    APELLIDO2_USUARIO_P IN VARCHAR2,
    EMAIL_USUARIO_P IN VARCHAR2,
    TELEFONO_USUARIO_P IN NUMBER,
    CONTRASENA_HASH_P IN VARCHAR2,
    COD_ESTADO_USUARIO_P IN NUMBER,
    CUR_USUARIO OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_USUARIO(COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO, EMAIL_USUARIO, TELEFONO_USUARIO, CONTRASENA_HASH, COD_ESTADO_USUARIO)
            VALUES (COD_USUARIO_P, NOMBRE_USUARIO_P, APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P, EMAIL_USUARIO_P, TELEFONO_USUARIO_P, CONTRASENA_HASH_P, COD_ESTADO_USUARIO_P);

        WHEN 'R' THEN
            OPEN CUR_USUARIO FOR
                SELECT COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO, EMAIL_USUARIO, TELEFONO_USUARIO, CONTRASENA_HASH, COD_ESTADO_USUARIO
                FROM JRGY_USUARIO
                WHERE COD_USUARIO = COD_USUARIO_P;

        WHEN 'U' THEN
            UPDATE JRGY_USUARIO
            SET NOMBRE_USUARIO      = NOMBRE_USUARIO_P,
                APELLIDO1_USUARIO   = APELLIDO1_USUARIO_P,
                APELLIDO2_USUARIO   = APELLIDO2_USUARIO_P,
                EMAIL_USUARIO       = EMAIL_USUARIO_P,
                TELEFONO_USUARIO    = TELEFONO_USUARIO_P,
                CONTRASENA_HASH     = CONTRASENA_HASH_P,
                COD_ESTADO_USUARIO  = COD_ESTADO_USUARIO_P
            WHERE COD_USUARIO = COD_USUARIO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-343, 'NO SE ENCONTRO EL CLIENTE');
            END IF;

        WHEN 'D' THEN
            DELETE FROM JRGY_USUARIO WHERE COD_USUARIO = COD_USUARIO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-343, 'NO SE ENCONTRO EL CLIENTE');
            END IF;

        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

-- CRUD empleado
CREATE OR REPLACE PROCEDURE CRUD_EMPLEADO(
    OPCION_P IN VARCHAR2,
    COD_EMPLEADO_P IN NUMBER,
    CARGO_EMPLEADO_P IN VARCHAR2,
    FECHA_CONTRATACION_P IN DATE,
    SALARIO_P IN NUMBER,
    COMISION_P IN NUMBER,
    COD_USUARIO_P IN NUMBER,
    NOMBRE_USUARIO_P IN VARCHAR2,
    APELLIDO1_USUARIO_P IN VARCHAR2,
    APELLIDO2_USUARIO_P IN VARCHAR2,
    EMAIL_USUARIO_P IN VARCHAR2,
    TELEFONO_USUARIO_P IN NUMBER,
    CONTRASENA_HASH_P IN VARCHAR2,
    COD_ESTADO_USUARIO_P IN NUMBER,
    COD_DEPARTAMENTO_P IN NUMBER,
    COD_ESTADO_LABORAL_P IN NUMBER,
    CUR_EMPLEADO OUT SYS_REFCURSOR
)
IS
    V_COD_USUARIO NUMBER := COD_USUARIO_P;
    CUR_USUARIO SYS_REFCURSOR;
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            IF V_COD_USUARIO IS NULL THEN
                SELECT SQ_PK_USUARIO.NEXTVAL INTO V_COD_USUARIO FROM DUAL;
            END IF;

            CRUD_USUARIO(
                'C',
                V_COD_USUARIO,
                NOMBRE_USUARIO_P,
                APELLIDO1_USUARIO_P,
                APELLIDO2_USUARIO_P,
                EMAIL_USUARIO_P,
                TELEFONO_USUARIO_P,
                CONTRASENA_HASH_P,
                COD_ESTADO_USUARIO_P,
                CUR_USUARIO
            );

            INSERT INTO JRGY_EMPLEADO(COD_EMPLEADO, COD_USUARIO, COD_DEPARTAMENTO, CARGO, FECHA_CONTRATACION, SALARIO, COMISION, COD_ESTADO_LABORAL)
            VALUES (COD_EMPLEADO_P, V_COD_USUARIO, COD_DEPARTAMENTO_P, CARGO_EMPLEADO_P, FECHA_CONTRATACION_P, SALARIO_P, COMISION_P, COD_ESTADO_LABORAL_P);

        WHEN 'R' THEN
            OPEN CUR_EMPLEADO FOR
                SELECT E.COD_EMPLEADO,
                       E.CARGO,
                       E.FECHA_CONTRATACION,
                       E.SALARIO,
                       E.COMISION,
                       U.COD_USUARIO,
                       U.NOMBRE_USUARIO,
                       U.APELLIDO1_USUARIO,
                       U.APELLIDO2_USUARIO,
                       U.EMAIL_USUARIO,
                       U.TELEFONO_USUARIO
                FROM JRGY_EMPLEADO E
                JOIN JRGY_USUARIO U ON U.COD_USUARIO = E.COD_USUARIO
                WHERE E.COD_EMPLEADO = COD_EMPLEADO_P;

        WHEN 'U' THEN
            CRUD_USUARIO(
                'U',
                V_COD_USUARIO,
                NOMBRE_USUARIO_P,
                APELLIDO1_USUARIO_P,
                APELLIDO2_USUARIO_P,
                EMAIL_USUARIO_P,
                TELEFONO_USUARIO_P,
                CONTRASENA_HASH_P,
                COD_ESTADO_USUARIO_P,
                CUR_USUARIO
            );

            UPDATE JRGY_EMPLEADO
            SET CARGO             = CARGO_EMPLEADO_P,
                FECHA_CONTRATACION = FECHA_CONTRATACION_P,
                SALARIO            = SALARIO_P,
                COMISION           = COMISION_P,
                COD_DEPARTAMENTO   = COD_DEPARTAMENTO_P,
                COD_ESTADO_LABORAL = COD_ESTADO_LABORAL_P
            WHERE COD_EMPLEADO = COD_EMPLEADO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-342, 'NO SE ENCONTRO EL EMPLEADO');
            END IF;

        WHEN 'D' THEN
            DELETE FROM JRGY_EMPLEADO WHERE COD_EMPLEADO = COD_EMPLEADO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-342, 'NO SE ENCONTRO EL EMPLEADO');
            END IF;

            CRUD_USUARIO(
                'D',
                V_COD_USUARIO,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                CUR_USUARIO
            );

        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

-- CRUD producto
CREATE OR REPLACE PROCEDURE CRUD_PRODUCTO(
    OPCION_P IN VARCHAR2,
    COD_PRODUCTO_P IN NUMBER,
    NOMBRE_PRODUCTO_P IN VARCHAR2,
    TIPO_PRODUCTO_P IN VARCHAR2,
    PRECIO_PRODUCTO_P IN NUMBER,
    CANTIDAD_PRODUCTO_P IN NUMBER,
    STOCK_PRODUCTO_P IN NUMBER,
    CUR_PRODUCTO OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_PRODUCTO(COD_PRODUCTO, NOMBRE_PRODUCTO, TIPO_PRODUCTO, PRECIO_PRODUCTO, CANTIDAD_PRODUCTO, STOCK_PRODUCTO)
            VALUES (COD_PRODUCTO_P, NOMBRE_PRODUCTO_P, TIPO_PRODUCTO_P, PRECIO_PRODUCTO_P, CANTIDAD_PRODUCTO_P, STOCK_PRODUCTO_P);

        WHEN 'R' THEN
            OPEN CUR_PRODUCTO FOR
                SELECT COD_PRODUCTO, NOMBRE_PRODUCTO, TIPO_PRODUCTO, PRECIO_PRODUCTO, CANTIDAD_PRODUCTO, STOCK_PRODUCTO
                FROM JRGY_PRODUCTO
                WHERE COD_PRODUCTO = COD_PRODUCTO_P;

        WHEN 'U' THEN
            UPDATE JRGY_PRODUCTO
            SET NOMBRE_PRODUCTO   = NOMBRE_PRODUCTO_P,
                TIPO_PRODUCTO     = TIPO_PRODUCTO_P,
                PRECIO_PRODUCTO   = PRECIO_PRODUCTO_P,
                CANTIDAD_PRODUCTO = CANTIDAD_PRODUCTO_P,
                STOCK_PRODUCTO    = STOCK_PRODUCTO_P
            WHERE COD_PRODUCTO = COD_PRODUCTO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-343, 'NO SE ENCONTRO EL PRODUCTO');
            END IF;

        WHEN 'D' THEN
            DELETE FROM JRGY_PRODUCTO WHERE COD_PRODUCTO = COD_PRODUCTO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-343, 'NO SE ENCONTRO EL PRODUCTO');
            END IF;

        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

-- Autenticacion simple
CREATE OR REPLACE PROCEDURE JRGY_PRO_LOGIN(
    EMAIL_P IN VARCHAR2,
    CONTRASENA_P IN VARCHAR2,
    CUR_LOGIN OUT SYS_REFCURSOR
)
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT
    FROM JRGY_USUARIO
    WHERE EMAIL_USUARIO = EMAIL_P
      AND CONTRASENA_HASH = CONTRASENA_P;

    IF V_COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20060, 'CREDENCIALES INVALIDAS');
    END IF;

    OPEN CUR_LOGIN FOR
        SELECT U.COD_USUARIO,
               U.NOMBRE_USUARIO,
               U.APELLIDO1_USUARIO,
               U.APELLIDO2_USUARIO,
               U.EMAIL_USUARIO,
               UR.COD_ROL
        FROM JRGY_USUARIO U
        LEFT JOIN JRGY_USUARIO_ROL UR ON UR.COD_USUARIO = U.COD_USUARIO
        WHERE U.EMAIL_USUARIO = EMAIL_P
          AND U.CONTRASENA_HASH = CONTRASENA_P;
END;
/

-- Manejo de pedidos
CREATE OR REPLACE PROCEDURE JRGY_PRO_INSERT_PEDIDO (
    COD_EMPLEADO_P IN JRGY_PEDIDO.COD_EMPLEADO%TYPE,
    DETALLES_P IN DETALLE_PEDIDO_TAB,
    COD_PEDIDO_OUT OUT JRGY_PEDIDO.COD_PEDIDO%TYPE
)
IS
    V_COD_PEDIDO JRGY_PEDIDO.COD_PEDIDO%TYPE;
    V_VALOR_TOTAL JRGY_PEDIDO.VALOR_TOTAL%TYPE := 0;
BEGIN
    V_COD_PEDIDO := SQ_PK_PEDIDO.NEXTVAL;

    FOR I IN 1 .. DETALLES_P.COUNT LOOP
        V_VALOR_TOTAL := V_VALOR_TOTAL + (DETALLES_P(I).CANTIDAD_PRODUCTO * DETALLES_P(I).PRECIO_COMPRA);
    END LOOP;

    INSERT INTO JRGY_PEDIDO (COD_PEDIDO, VALOR_TOTAL, FECHA_PEDIDO, COD_EMPLEADO)
    VALUES (V_COD_PEDIDO, V_VALOR_TOTAL, SYSDATE, COD_EMPLEADO_P);

    FOR I IN 1 .. DETALLES_P.COUNT LOOP
        INSERT INTO JRGY_DETALLE_PEDIDO (COD_PEDIDO, COD_PROVEEDOR, COD_PRODUCTO, NOMBRE_PRODUCTO, CANTIDAD_PRODUCTO, PRECIO_COMPRA, PRECIO_TOTAL)
        VALUES (
            V_COD_PEDIDO,
            DETALLES_P(I).COD_PROVEEDOR,
            DETALLES_P(I).COD_PRODUCTO,
            DETALLES_P(I).NOMBRE_PRODUCTO,
            DETALLES_P(I).CANTIDAD_PRODUCTO,
            DETALLES_P(I).PRECIO_COMPRA,
            DETALLES_P(I).CANTIDAD_PRODUCTO * DETALLES_P(I).PRECIO_COMPRA
        );

    END LOOP;

    COD_PEDIDO_OUT := V_COD_PEDIDO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20011, 'Error al insertar el pedido: ' || SQLERRM);
END JRGY_PRO_INSERT_PEDIDO;
/

CREATE OR REPLACE PACKAGE PKG_PEDIDO IS
    TYPE CURSOR_P IS REF CURSOR;
    PROCEDURE JRGY_PRO_GET_PEDIDO_DETALLE (
        COD_PEDIDO_P IN JRGY_PEDIDO.COD_PEDIDO%TYPE,
        CURSOR_P OUT CURSOR_P
    );
END PKG_PEDIDO;
/

CREATE OR REPLACE PACKAGE BODY PKG_PEDIDO IS
    PROCEDURE JRGY_PRO_GET_PEDIDO_DETALLE (
        COD_PEDIDO_P IN JRGY_PEDIDO.COD_PEDIDO%TYPE,
        CURSOR_P OUT CURSOR_P
    ) IS
    BEGIN
        OPEN CURSOR_P FOR
            SELECT P.COD_PEDIDO,
                   P.FECHA_PEDIDO,
                   P.VALOR_TOTAL AS VALOR_TOTAL_PEDIDO,
                   DP.COD_PROVEEDOR,
                   DP.NOMBRE_PRODUCTO,
                   DP.CANTIDAD_PRODUCTO,
                   DP.PRECIO_COMPRA,
                   DP.PRECIO_TOTAL AS VALOR_TOTAL_DETALLE
            FROM JRGY_PEDIDO P
            JOIN JRGY_DETALLE_PEDIDO DP ON DP.COD_PEDIDO = P.COD_PEDIDO
            WHERE P.COD_PEDIDO = COD_PEDIDO_P;
    END JRGY_PRO_GET_PEDIDO_DETALLE;
END PKG_PEDIDO;
/

CREATE OR REPLACE PROCEDURE JRGY_PRO_UPDATE_PEDIDO_TOTAL (
    COD_PEDIDO_P IN JRGY_PEDIDO.COD_PEDIDO%TYPE
)
IS
    NUEVO_TOTAL JRGY_PEDIDO.VALOR_TOTAL%TYPE;
BEGIN
    SELECT NVL(SUM(PRECIO_TOTAL), 0)
    INTO NUEVO_TOTAL
    FROM JRGY_DETALLE_PEDIDO
    WHERE COD_PEDIDO = COD_PEDIDO_P;

    UPDATE JRGY_PEDIDO
    SET VALOR_TOTAL = NUEVO_TOTAL
    WHERE COD_PEDIDO = COD_PEDIDO_P;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20012, 'Pedido con código ' || COD_PEDIDO_P || ' no encontrado.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20013, 'Error al recalcular y actualizar total del pedido: ' || SQLERRM);
END JRGY_PRO_UPDATE_PEDIDO_TOTAL;
/

CREATE OR REPLACE PROCEDURE JRGY_PRO_DELETE_PEDIDO (
    COD_PEDIDO_P IN JRGY_PEDIDO.COD_PEDIDO%TYPE
)
IS
    PEDIDOS_ELIMINADOS NUMBER;
BEGIN
    DELETE FROM JRGY_PEDIDO WHERE COD_PEDIDO = COD_PEDIDO_P;
    PEDIDOS_ELIMINADOS := SQL%ROWCOUNT;

    IF PEDIDOS_ELIMINADOS = 0 THEN
        RAISE_APPLICATION_ERROR(-20014, 'Pedido con código ' || COD_PEDIDO_P || ' no encontrado para eliminar.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20015, 'Error al eliminar el pedido: ' || SQLERRM);
END JRGY_PRO_DELETE_PEDIDO;
/

-- CRUD rol
CREATE OR REPLACE PROCEDURE CRUD_ROL(
    OPCION_P IN VARCHAR2,
    COD_ROL_P IN NUMBER,
    NOMBRE_ROL_P IN VARCHAR2,
    CUR_ROL OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_ROL (COD_ROL, NOMBRE_ROL)
            VALUES (COD_ROL_P, NOMBRE_ROL_P);
        WHEN 'R' THEN
            OPEN CUR_ROL FOR
                SELECT COD_ROL, NOMBRE_ROL
                FROM JRGY_ROL
                WHERE COD_ROL = COD_ROL_P;
        WHEN 'U' THEN
            UPDATE JRGY_ROL
            SET NOMBRE_ROL = NOMBRE_ROL_P
            WHERE COD_ROL = COD_ROL_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20020, 'ROL NO ENCONTRADO');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_ROL WHERE COD_ROL = COD_ROL_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20020, 'ROL NO ENCONTRADO');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

-- CRUD usuario_rol
CREATE OR REPLACE PROCEDURE CRUD_USUARIO_ROL(
    OPCION_P IN VARCHAR2,
    COD_USUARIO_P IN NUMBER,
    COD_ROL_P IN NUMBER,
    CUR_USUARIO_ROL OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_USUARIO_ROL (COD_USUARIO, COD_ROL)
            VALUES (COD_USUARIO_P, COD_ROL_P);
        WHEN 'R' THEN
            OPEN CUR_USUARIO_ROL FOR
                SELECT COD_USUARIO, COD_ROL
                FROM JRGY_USUARIO_ROL
                WHERE COD_USUARIO = COD_USUARIO_P AND COD_ROL = COD_ROL_P;
        WHEN 'U' THEN
            RAISE_APPLICATION_ERROR(-20021, 'UPDATE NO SOPORTADO, ELIMINE Y CREE NUEVO');
        WHEN 'D' THEN
            DELETE FROM JRGY_USUARIO_ROL
            WHERE COD_USUARIO = COD_USUARIO_P AND COD_ROL = COD_ROL_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20021, 'ASIGNACION NO ENCONTRADA');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

-- CRUD region / ciudad / comuna / calle
CREATE OR REPLACE PROCEDURE CRUD_REGION(
    OPCION_P IN VARCHAR2,
    COD_REGION_P IN NUMBER,
    REGION_P IN VARCHAR2,
    CUR_REGION OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_REGION (COD_REGION, REGION) VALUES (COD_REGION_P, REGION_P);
        WHEN 'R' THEN
            OPEN CUR_REGION FOR
                SELECT COD_REGION, REGION FROM JRGY_REGION WHERE COD_REGION = COD_REGION_P;
        WHEN 'U' THEN
            UPDATE JRGY_REGION SET REGION = REGION_P WHERE COD_REGION = COD_REGION_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20022, 'REGION NO ENCONTRADA');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_REGION WHERE COD_REGION = COD_REGION_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20022, 'REGION NO ENCONTRADA');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

CREATE OR REPLACE PROCEDURE CRUD_CIUDAD(
    OPCION_P IN VARCHAR2,
    COD_CIUDAD_P IN NUMBER,
    CIUDAD_P IN VARCHAR2,
    COD_REGION_P IN NUMBER,
    CUR_CIUDAD OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_CIUDAD (COD_CIUDAD, CIUDAD, COD_REGION) VALUES (COD_CIUDAD_P, CIUDAD_P, COD_REGION_P);
        WHEN 'R' THEN
            OPEN CUR_CIUDAD FOR
                SELECT COD_CIUDAD, CIUDAD, COD_REGION FROM JRGY_CIUDAD WHERE COD_CIUDAD = COD_CIUDAD_P;
        WHEN 'U' THEN
            UPDATE JRGY_CIUDAD
            SET CIUDAD = CIUDAD_P,
                COD_REGION = COD_REGION_P
            WHERE COD_CIUDAD = COD_CIUDAD_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20023, 'CIUDAD NO ENCONTRADA');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_CIUDAD WHERE COD_CIUDAD = COD_CIUDAD_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20023, 'CIUDAD NO ENCONTRADA');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

CREATE OR REPLACE PROCEDURE CRUD_COMUNA(
    OPCION_P IN VARCHAR2,
    COD_COMUNA_P IN NUMBER,
    COMUNA_P IN VARCHAR2,
    COD_CIUDAD_P IN NUMBER,
    CUR_COMUNA OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_COMUNA (COD_COMUNA, COMUNA, COD_CIUDAD) VALUES (COD_COMUNA_P, COMUNA_P, COD_CIUDAD_P);
        WHEN 'R' THEN
            OPEN CUR_COMUNA FOR
                SELECT COD_COMUNA, COMUNA, COD_CIUDAD FROM JRGY_COMUNA WHERE COD_COMUNA = COD_COMUNA_P;
        WHEN 'U' THEN
            UPDATE JRGY_COMUNA
            SET COMUNA = COMUNA_P,
                COD_CIUDAD = COD_CIUDAD_P
            WHERE COD_COMUNA = COD_COMUNA_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20024, 'COMUNA NO ENCONTRADA');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_COMUNA WHERE COD_COMUNA = COD_COMUNA_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20024, 'COMUNA NO ENCONTRADA');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

CREATE OR REPLACE PROCEDURE CRUD_CALLE(
    OPCION_P IN VARCHAR2,
    COD_CALLE_P IN NUMBER,
    CALLE_P IN VARCHAR2,
    NRO_P IN NUMBER,
    COD_COMUNA_P IN NUMBER,
    CUR_CALLE OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_CALLE (COD_CALLE, CALLE, NRO, COD_COMUNA) VALUES (COD_CALLE_P, CALLE_P, NRO_P, COD_COMUNA_P);
        WHEN 'R' THEN
            OPEN CUR_CALLE FOR
                SELECT COD_CALLE, CALLE, NRO, COD_COMUNA FROM JRGY_CALLE WHERE COD_CALLE = COD_CALLE_P;
        WHEN 'U' THEN
            UPDATE JRGY_CALLE
            SET CALLE = CALLE_P,
                NRO = NRO_P,
                COD_COMUNA = COD_COMUNA_P
            WHERE COD_CALLE = COD_CALLE_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20025, 'CALLE NO ENCONTRADA');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_CALLE WHERE COD_CALLE = COD_CALLE_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20025, 'CALLE NO ENCONTRADA');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

-- CRUD proveedor
CREATE OR REPLACE PROCEDURE CRUD_PROVEEDOR(
    OPCION_P IN VARCHAR2,
    COD_PROVEEDOR_P IN NUMBER,
    NOMBRE_PROVEEDOR_P IN VARCHAR2,
    DIRECCION_PROVEEDOR_P IN VARCHAR2,
    TELEFONO_PROVEEDOR_P IN NUMBER,
    COD_REGION_P IN NUMBER,
    CUR_PROVEEDOR OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_PROVEEDOR (COD_PROVEEDOR, NOMBRE_PROVEEDOR, DIRECCION_PROVEEDOR, TELEFONO_PROVEEDOR, COD_REGION)
            VALUES (COD_PROVEEDOR_P, NOMBRE_PROVEEDOR_P, DIRECCION_PROVEEDOR_P, TELEFONO_PROVEEDOR_P, COD_REGION_P);
        WHEN 'R' THEN
            OPEN CUR_PROVEEDOR FOR
                SELECT COD_PROVEEDOR, NOMBRE_PROVEEDOR, DIRECCION_PROVEEDOR, TELEFONO_PROVEEDOR, COD_REGION
                FROM JRGY_PROVEEDOR
                WHERE COD_PROVEEDOR = COD_PROVEEDOR_P;
        WHEN 'U' THEN
            UPDATE JRGY_PROVEEDOR
            SET NOMBRE_PROVEEDOR   = NOMBRE_PROVEEDOR_P,
                DIRECCION_PROVEEDOR = DIRECCION_PROVEEDOR_P,
                TELEFONO_PROVEEDOR  = TELEFONO_PROVEEDOR_P,
                COD_REGION          = COD_REGION_P
            WHERE COD_PROVEEDOR = COD_PROVEEDOR_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20026, 'PROVEEDOR NO ENCONTRADO');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_PROVEEDOR WHERE COD_PROVEEDOR = COD_PROVEEDOR_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20026, 'PROVEEDOR NO ENCONTRADO');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

-- CRUD habitacion y pagos
CREATE OR REPLACE PROCEDURE CRUD_HABITACION(
    OPCION_P IN VARCHAR2,
    COD_HABITACION_P IN NUMBER,
    NRO_HABITACION_P IN NUMBER,
    CAPACIDAD_P IN NUMBER,
    COD_TIPO_HABITACION_P IN NUMBER,
    COD_ESTADO_HABITACION_P IN NUMBER,
    PRECIO_BASE_P IN NUMBER,
    CUR_HABITACION OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_HABITACION (COD_HABITACION, NRO_HABITACION, CAPACIDAD, COD_TIPO_HABITACION, COD_ESTADO_HABITACION, PRECIO_BASE)
            VALUES (COD_HABITACION_P, NRO_HABITACION_P, CAPACIDAD_P, COD_TIPO_HABITACION_P, COD_ESTADO_HABITACION_P, PRECIO_BASE_P);
        WHEN 'R' THEN
            OPEN CUR_HABITACION FOR
                SELECT COD_HABITACION, NRO_HABITACION, CAPACIDAD, COD_TIPO_HABITACION, COD_ESTADO_HABITACION, PRECIO_BASE
                FROM JRGY_HABITACION
                WHERE COD_HABITACION = COD_HABITACION_P;
        WHEN 'U' THEN
            UPDATE JRGY_HABITACION
            SET NRO_HABITACION      = NRO_HABITACION_P,
                CAPACIDAD           = CAPACIDAD_P,
                COD_TIPO_HABITACION = COD_TIPO_HABITACION_P,
                COD_ESTADO_HABITACION = COD_ESTADO_HABITACION_P,
                PRECIO_BASE         = PRECIO_BASE_P
            WHERE COD_HABITACION = COD_HABITACION_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20027, 'HABITACION NO ENCONTRADA');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_HABITACION WHERE COD_HABITACION = COD_HABITACION_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20027, 'HABITACION NO ENCONTRADA');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

CREATE OR REPLACE PROCEDURE CRUD_PAGO_HABITACION(
    OPCION_P IN VARCHAR2,
    COD_PAGO_P IN NUMBER,
    FECHA_PAGO_P IN DATE,
    VALOR_TOTAL_P IN NUMBER,
    COD_USUARIO_P IN NUMBER,
    CUR_PAGO OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_PAGO_HABITACION (COD_PAGO_HABITACION, FECHA_PAGO, VALOR_TOTAL_PAGO, COD_USUARIO)
            VALUES (COD_PAGO_P, FECHA_PAGO_P, VALOR_TOTAL_P, COD_USUARIO_P);
        WHEN 'R' THEN
            OPEN CUR_PAGO FOR
                SELECT COD_PAGO_HABITACION, FECHA_PAGO, VALOR_TOTAL_PAGO, COD_USUARIO
                FROM JRGY_PAGO_HABITACION
                WHERE COD_PAGO_HABITACION = COD_PAGO_P;
        WHEN 'U' THEN
            UPDATE JRGY_PAGO_HABITACION
            SET FECHA_PAGO = FECHA_PAGO_P,
                VALOR_TOTAL_PAGO = VALOR_TOTAL_P,
                COD_USUARIO = COD_USUARIO_P
            WHERE COD_PAGO_HABITACION = COD_PAGO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20028, 'PAGO HABITACION NO ENCONTRADO');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_PAGO_HABITACION WHERE COD_PAGO_HABITACION = COD_PAGO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20028, 'PAGO HABITACION NO ENCONTRADO');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

CREATE OR REPLACE PROCEDURE CRUD_DETALLE_PAGO_HABITACION(
    OPCION_P IN VARCHAR2,
    COD_PAGO_P IN NUMBER,
    COD_HABITACION_P IN NUMBER,
    FECHA_ESTADIA_P IN DATE,
    PRECIO_HABITACION_P IN NUMBER,
    DIAS_P IN NUMBER,
    CUR_DET_PAGO OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_DETALLE_PAGO_HABITACION (COD_PAGO_HABITACION, COD_HABITACION, FECHA_ESTADIA, PRECIO_HABITACION, DIAS)
            VALUES (COD_PAGO_P, COD_HABITACION_P, FECHA_ESTADIA_P, PRECIO_HABITACION_P, DIAS_P);
        WHEN 'R' THEN
            OPEN CUR_DET_PAGO FOR
                SELECT COD_PAGO_HABITACION, COD_HABITACION, FECHA_ESTADIA, PRECIO_HABITACION, DIAS
                FROM JRGY_DETALLE_PAGO_HABITACION
                WHERE COD_PAGO_HABITACION = COD_PAGO_P AND COD_HABITACION = COD_HABITACION_P;
        WHEN 'U' THEN
            UPDATE JRGY_DETALLE_PAGO_HABITACION
            SET FECHA_ESTADIA = FECHA_ESTADIA_P,
                PRECIO_HABITACION = PRECIO_HABITACION_P,
                DIAS = DIAS_P
            WHERE COD_PAGO_HABITACION = COD_PAGO_P AND COD_HABITACION = COD_HABITACION_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20029, 'DETALLE PAGO HAB NO ENCONTRADO');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_DETALLE_PAGO_HABITACION
            WHERE COD_PAGO_HABITACION = COD_PAGO_P AND COD_HABITACION = COD_HABITACION_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20029, 'DETALLE PAGO HAB NO ENCONTRADO');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

-- CRUD pedido/detalle
CREATE OR REPLACE PROCEDURE CRUD_PEDIDO(
    OPCION_P IN VARCHAR2,
    COD_PEDIDO_P IN NUMBER,
    VALOR_TOTAL_P IN NUMBER,
    FECHA_PEDIDO_P IN DATE,
    COD_EMPLEADO_P IN NUMBER,
    CUR_PEDIDO OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_PEDIDO (COD_PEDIDO, VALOR_TOTAL, FECHA_PEDIDO, COD_EMPLEADO)
            VALUES (COD_PEDIDO_P, VALOR_TOTAL_P, FECHA_PEDIDO_P, COD_EMPLEADO_P);
        WHEN 'R' THEN
            OPEN CUR_PEDIDO FOR
                SELECT COD_PEDIDO, VALOR_TOTAL, FECHA_PEDIDO, COD_EMPLEADO
                FROM JRGY_PEDIDO
                WHERE COD_PEDIDO = COD_PEDIDO_P;
        WHEN 'U' THEN
            UPDATE JRGY_PEDIDO
            SET VALOR_TOTAL = VALOR_TOTAL_P,
                FECHA_PEDIDO = FECHA_PEDIDO_P,
                COD_EMPLEADO = COD_EMPLEADO_P
            WHERE COD_PEDIDO = COD_PEDIDO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20030, 'PEDIDO NO ENCONTRADO');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_PEDIDO WHERE COD_PEDIDO = COD_PEDIDO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20030, 'PEDIDO NO ENCONTRADO');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

CREATE OR REPLACE PROCEDURE CRUD_DETALLE_PEDIDO(
    OPCION_P IN VARCHAR2,
    COD_PEDIDO_P IN NUMBER,
    COD_PROVEEDOR_P IN NUMBER,
    COD_PRODUCTO_P IN NUMBER,
    NOMBRE_PRODUCTO_P IN VARCHAR2,
    CANTIDAD_PRODUCTO_P IN NUMBER,
    PRECIO_COMPRA_P IN NUMBER,
    PRECIO_TOTAL_P IN NUMBER,
    CUR_DET_PEDIDO OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_DETALLE_PEDIDO (COD_PEDIDO, COD_PROVEEDOR, COD_PRODUCTO, NOMBRE_PRODUCTO, CANTIDAD_PRODUCTO, PRECIO_COMPRA, PRECIO_TOTAL)
            VALUES (COD_PEDIDO_P, COD_PROVEEDOR_P, COD_PRODUCTO_P, NOMBRE_PRODUCTO_P, CANTIDAD_PRODUCTO_P, PRECIO_COMPRA_P, PRECIO_TOTAL_P);
        WHEN 'R' THEN
            OPEN CUR_DET_PEDIDO FOR
                SELECT COD_PEDIDO, COD_PROVEEDOR, COD_PRODUCTO, NOMBRE_PRODUCTO, CANTIDAD_PRODUCTO, PRECIO_COMPRA, PRECIO_TOTAL
                FROM JRGY_DETALLE_PEDIDO
                WHERE COD_PEDIDO = COD_PEDIDO_P AND COD_PROVEEDOR = COD_PROVEEDOR_P AND COD_PRODUCTO = COD_PRODUCTO_P;
        WHEN 'U' THEN
            UPDATE JRGY_DETALLE_PEDIDO
            SET COD_PRODUCTO      = COD_PRODUCTO_P,
                NOMBRE_PRODUCTO   = NOMBRE_PRODUCTO_P,
                CANTIDAD_PRODUCTO = CANTIDAD_PRODUCTO_P,
                PRECIO_COMPRA     = PRECIO_COMPRA_P,
                PRECIO_TOTAL      = PRECIO_TOTAL_P
            WHERE COD_PEDIDO = COD_PEDIDO_P AND COD_PROVEEDOR = COD_PROVEEDOR_P AND COD_PRODUCTO = COD_PRODUCTO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20031, 'DETALLE PEDIDO NO ENCONTRADO');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_DETALLE_PEDIDO WHERE COD_PEDIDO = COD_PEDIDO_P AND COD_PROVEEDOR = COD_PROVEEDOR_P AND COD_PRODUCTO = COD_PRODUCTO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20031, 'DETALLE PEDIDO NO ENCONTRADO');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

-- CRUD venta/detalle
CREATE OR REPLACE PROCEDURE CRUD_VENTA(
    OPCION_P IN VARCHAR2,
    COD_VENTA_P IN NUMBER,
    COD_USUARIO_P IN NUMBER,
    COD_EMPLEADO_P IN NUMBER,
    FECHA_VENTA_P IN DATE,
    CUR_VENTA OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_VENTA (COD_VENTA, COD_USUARIO, COD_EMPLEADO, FECHA_VENTA)
            VALUES (COD_VENTA_P, COD_USUARIO_P, COD_EMPLEADO_P, FECHA_VENTA_P);
        WHEN 'R' THEN
            OPEN CUR_VENTA FOR
                SELECT COD_VENTA, COD_USUARIO, COD_EMPLEADO, FECHA_VENTA
                FROM JRGY_VENTA
                WHERE COD_VENTA = COD_VENTA_P;
        WHEN 'U' THEN
            UPDATE JRGY_VENTA
            SET COD_USUARIO = COD_USUARIO_P,
                COD_EMPLEADO = COD_EMPLEADO_P,
                FECHA_VENTA = FECHA_VENTA_P
            WHERE COD_VENTA = COD_VENTA_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20032, 'VENTA NO ENCONTRADA');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_VENTA WHERE COD_VENTA = COD_VENTA_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20032, 'VENTA NO ENCONTRADA');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

CREATE OR REPLACE PROCEDURE CRUD_DETALLE_VENTA(
    OPCION_P IN VARCHAR2,
    COD_VENTA_P IN NUMBER,
    COD_PRODUCTO_P IN NUMBER,
    CANTIDAD_P IN NUMBER,
    PRECIO_PRODUCTO_P IN NUMBER,
    PRECIO_TOTAL_P IN NUMBER,
    CUR_DET_VENTA OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_DETALLE_VENTA (COD_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_PRODUCTO, PRECIO_TOTAL)
            VALUES (COD_VENTA_P, COD_PRODUCTO_P, CANTIDAD_P, PRECIO_PRODUCTO_P, PRECIO_TOTAL_P);
        WHEN 'R' THEN
            OPEN CUR_DET_VENTA FOR
                SELECT COD_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_PRODUCTO, PRECIO_TOTAL
                FROM JRGY_DETALLE_VENTA
                WHERE COD_VENTA = COD_VENTA_P AND COD_PRODUCTO = COD_PRODUCTO_P;
        WHEN 'U' THEN
            UPDATE JRGY_DETALLE_VENTA
            SET CANTIDAD = CANTIDAD_P,
                PRECIO_PRODUCTO = PRECIO_PRODUCTO_P,
                PRECIO_TOTAL = PRECIO_TOTAL_P
            WHERE COD_VENTA = COD_VENTA_P AND COD_PRODUCTO = COD_PRODUCTO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20033, 'DETALLE VENTA NO ENCONTRADO');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_DETALLE_VENTA WHERE COD_VENTA = COD_VENTA_P AND COD_PRODUCTO = COD_PRODUCTO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20033, 'DETALLE VENTA NO ENCONTRADO');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

-- CRUD movimiento stock
CREATE OR REPLACE PROCEDURE CRUD_MOVIMIENTO_STOCK(
    OPCION_P IN VARCHAR2,
    COD_MOVIMIENTO_P IN NUMBER,
    COD_PRODUCTO_P IN NUMBER,
    TIPO_MOVIMIENTO_P IN VARCHAR2,
    CANTIDAD_P IN NUMBER,
    FECHA_MOVIMIENTO_P IN DATE,
    MOTIVO_P IN VARCHAR2,
    CUR_MOV OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_MOVIMIENTO_STOCK (COD_MOVIMIENTO, COD_PRODUCTO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, MOTIVO)
            VALUES (COD_MOVIMIENTO_P, COD_PRODUCTO_P, TIPO_MOVIMIENTO_P, CANTIDAD_P, FECHA_MOVIMIENTO_P, MOTIVO_P);
        WHEN 'R' THEN
            OPEN CUR_MOV FOR
                SELECT COD_MOVIMIENTO, COD_PRODUCTO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, MOTIVO
                FROM JRGY_MOVIMIENTO_STOCK
                WHERE COD_MOVIMIENTO = COD_MOVIMIENTO_P;
        WHEN 'U' THEN
            UPDATE JRGY_MOVIMIENTO_STOCK
            SET COD_PRODUCTO = COD_PRODUCTO_P,
                TIPO_MOVIMIENTO = TIPO_MOVIMIENTO_P,
                CANTIDAD = CANTIDAD_P,
                FECHA_MOVIMIENTO = FECHA_MOVIMIENTO_P,
                MOTIVO = MOTIVO_P
            WHERE COD_MOVIMIENTO = COD_MOVIMIENTO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20034, 'MOVIMIENTO NO ENCONTRADO');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_MOVIMIENTO_STOCK WHERE COD_MOVIMIENTO = COD_MOVIMIENTO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20034, 'MOVIMIENTO NO ENCONTRADO');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

-- CRUD pago venta
CREATE OR REPLACE PROCEDURE CRUD_PAGO_VENTA(
    OPCION_P IN VARCHAR2,
    COD_PAGO_P IN NUMBER,
    COD_VENTA_P IN NUMBER,
    COD_MODO_PAGO_P IN NUMBER,
    MONTO_P IN NUMBER,
    FECHA_PAGO_P IN DATE,
    CUR_PAGO_VENTA OUT SYS_REFCURSOR
)
IS
BEGIN
    CASE UPPER(OPCION_P)
        WHEN 'C' THEN
            INSERT INTO JRGY_PAGO_VENTA (COD_PAGO, COD_VENTA, COD_MODO_PAGO, MONTO, FECHA_PAGO)
            VALUES (COD_PAGO_P, COD_VENTA_P, COD_MODO_PAGO_P, MONTO_P, FECHA_PAGO_P);
        WHEN 'R' THEN
            OPEN CUR_PAGO_VENTA FOR
                SELECT COD_PAGO, COD_VENTA, COD_MODO_PAGO, MONTO, FECHA_PAGO
                FROM JRGY_PAGO_VENTA
                WHERE COD_PAGO = COD_PAGO_P;
        WHEN 'U' THEN
            UPDATE JRGY_PAGO_VENTA
            SET COD_VENTA = COD_VENTA_P,
                COD_MODO_PAGO = COD_MODO_PAGO_P,
                MONTO = MONTO_P,
                FECHA_PAGO = FECHA_PAGO_P
            WHERE COD_PAGO = COD_PAGO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20035, 'PAGO VENTA NO ENCONTRADO');
            END IF;
        WHEN 'D' THEN
            DELETE FROM JRGY_PAGO_VENTA WHERE COD_PAGO = COD_PAGO_P;
            IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20035, 'PAGO VENTA NO ENCONTRADO');
            END IF;
        ELSE
            RAISE_APPLICATION_ERROR(-2003, 'INGRESE C R U D');
    END CASE;
END;
/

-- Tipos auxiliares para gestores (ya creados arriba)

-- Funciones de apoyo
CREATE OR REPLACE FUNCTION FN_CALC_IVA(MONTO IN NUMBER) RETURN NUMBER IS
BEGIN
    RETURN ROUND(MONTO * 0.19, 2);
END;
/

CREATE OR REPLACE FUNCTION FN_CALC_COMISION(COD_EMPLEADO_P IN NUMBER, MONTO_VENTA IN NUMBER) RETURN NUMBER IS
    PCT NUMBER;
BEGIN
    SELECT NVL(COMISION, 0) INTO PCT FROM JRGY_EMPLEADO WHERE COD_EMPLEADO = COD_EMPLEADO_P;
    RETURN ROUND(MONTO_VENTA * (PCT / 100), 2);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_STOCK_DISP(COD_PRODUCTO_P IN NUMBER) RETURN NUMBER IS
    STK NUMBER;
BEGIN
    SELECT NVL(STOCK_PRODUCTO, 0) INTO STK FROM JRGY_PRODUCTO WHERE COD_PRODUCTO = COD_PRODUCTO_P;
    RETURN STK;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

-- Gestor: registrar venta con detalle, stock y movimientos
CREATE OR REPLACE PROCEDURE JRGY_PRO_REGISTRAR_VENTA (
    COD_USUARIO_P IN NUMBER,
    COD_EMPLEADO_P IN NUMBER,
    DETALLES_P IN DETALLE_VENTA_TAB,
    COD_VENTA_OUT OUT NUMBER,
    TOTAL_OUT OUT NUMBER
)
IS
    V_COD_VENTA NUMBER;
    V_TOTAL NUMBER := 0;
BEGIN
    IF DETALLES_P IS NULL OR DETALLES_P.COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20040, 'DEBE ENVIAR DETALLES DE VENTA');
    END IF;

    V_COD_VENTA := SQ_PK_VENTA.NEXTVAL;

    FOR I IN 1 .. DETALLES_P.COUNT LOOP
        IF FN_STOCK_DISP(DETALLES_P(I).COD_PRODUCTO) < DETALLES_P(I).CANTIDAD THEN
            RAISE_APPLICATION_ERROR(-20041, 'STOCK INSUFICIENTE PARA PRODUCTO ' || DETALLES_P(I).COD_PRODUCTO);
        END IF;
        V_TOTAL := V_TOTAL + (DETALLES_P(I).CANTIDAD * DETALLES_P(I).PRECIO_PRODUCTO);
    END LOOP;

    INSERT INTO JRGY_VENTA (COD_VENTA, COD_USUARIO, COD_EMPLEADO, FECHA_VENTA)
    VALUES (V_COD_VENTA, COD_USUARIO_P, COD_EMPLEADO_P, SYSDATE);

    FOR I IN 1 .. DETALLES_P.COUNT LOOP
        INSERT INTO JRGY_DETALLE_VENTA (COD_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_PRODUCTO, PRECIO_TOTAL)
        VALUES (V_COD_VENTA, DETALLES_P(I).COD_PRODUCTO, DETALLES_P(I).CANTIDAD, DETALLES_P(I).PRECIO_PRODUCTO, DETALLES_P(I).CANTIDAD * DETALLES_P(I).PRECIO_PRODUCTO);

        UPDATE JRGY_PRODUCTO
        SET STOCK_PRODUCTO = STOCK_PRODUCTO - DETALLES_P(I).CANTIDAD
        WHERE COD_PRODUCTO = DETALLES_P(I).COD_PRODUCTO;

        INSERT INTO JRGY_MOVIMIENTO_STOCK (COD_MOVIMIENTO, COD_PRODUCTO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, MOTIVO)
        VALUES (SQ_PK_MOVIMIENTO_STOCK.NEXTVAL, DETALLES_P(I).COD_PRODUCTO, 'SALIDA', DETALLES_P(I).CANTIDAD, SYSDATE, 'VENTA ' || V_COD_VENTA);
    END LOOP;

    COD_VENTA_OUT := V_COD_VENTA;
    TOTAL_OUT := V_TOTAL;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Gestor: registrar pedido (recalcula total)
CREATE OR REPLACE PROCEDURE JRGY_PRO_REGISTRAR_PEDIDO (
    COD_EMPLEADO_P IN NUMBER,
    DETALLES_P IN DETALLE_PEDIDO_TAB,
    COD_PEDIDO_OUT OUT NUMBER,
    TOTAL_OUT OUT NUMBER
)
IS
    V_COD_PEDIDO NUMBER;
    V_TOTAL NUMBER := 0;
BEGIN
    IF DETALLES_P IS NULL OR DETALLES_P.COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20042, 'DEBE ENVIAR DETALLES DE PEDIDO');
    END IF;

    V_COD_PEDIDO := SQ_PK_PEDIDO.NEXTVAL;

    FOR I IN 1 .. DETALLES_P.COUNT LOOP
        V_TOTAL := V_TOTAL + (DETALLES_P(I).CANTIDAD_PRODUCTO * DETALLES_P(I).PRECIO_COMPRA);
    END LOOP;

    INSERT INTO JRGY_PEDIDO (COD_PEDIDO, VALOR_TOTAL, FECHA_PEDIDO, COD_EMPLEADO)
    VALUES (V_COD_PEDIDO, V_TOTAL, SYSDATE, COD_EMPLEADO_P);

    FOR I IN 1 .. DETALLES_P.COUNT LOOP
        INSERT INTO JRGY_DETALLE_PEDIDO (COD_PEDIDO, COD_PROVEEDOR, COD_PRODUCTO, NOMBRE_PRODUCTO, CANTIDAD_PRODUCTO, PRECIO_COMPRA, PRECIO_TOTAL)
        VALUES (
            V_COD_PEDIDO,
            DETALLES_P(I).COD_PROVEEDOR,
            DETALLES_P(I).COD_PRODUCTO,
            DETALLES_P(I).NOMBRE_PRODUCTO,
            DETALLES_P(I).CANTIDAD_PRODUCTO,
            DETALLES_P(I).PRECIO_COMPRA,
            DETALLES_P(I).CANTIDAD_PRODUCTO * DETALLES_P(I).PRECIO_COMPRA
        );

        UPDATE JRGY_PRODUCTO
        SET STOCK_PRODUCTO = NVL(STOCK_PRODUCTO, 0) + DETALLES_P(I).CANTIDAD_PRODUCTO
        WHERE COD_PRODUCTO = DETALLES_P(I).COD_PRODUCTO;

        INSERT INTO JRGY_MOVIMIENTO_STOCK (COD_MOVIMIENTO, COD_PRODUCTO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, MOTIVO)
        VALUES (SQ_PK_MOVIMIENTO_STOCK.NEXTVAL, DETALLES_P(I).COD_PRODUCTO, 'ENTRADA', DETALLES_P(I).CANTIDAD_PRODUCTO, SYSDATE, 'PEDIDO ' || V_COD_PEDIDO);
    END LOOP;

    COD_PEDIDO_OUT := V_COD_PEDIDO;
    TOTAL_OUT := V_TOTAL;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Gestor: pago de habitación con detalle y cambio de estado
CREATE OR REPLACE PROCEDURE JRGY_PRO_PAGO_HABITACION (
    COD_USUARIO_P IN NUMBER,
    DETALLES_P IN DETALLE_ESTADIA_TAB,
    COD_PAGO_OUT OUT NUMBER,
    TOTAL_OUT OUT NUMBER
)
IS
    V_COD_PAGO NUMBER;
    V_TOTAL NUMBER := 0;
BEGIN
    IF DETALLES_P IS NULL OR DETALLES_P.COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20043, 'DEBE ENVIAR DETALLES DE ESTADIA');
    END IF;

    V_COD_PAGO := SQ_PK_PAGO_HAB.NEXTVAL;

    FOR I IN 1 .. DETALLES_P.COUNT LOOP
        V_TOTAL := V_TOTAL + (DETALLES_P(I).PRECIO_HABITACION * DETALLES_P(I).DIAS);
    END LOOP;

    INSERT INTO JRGY_PAGO_HABITACION (COD_PAGO_HABITACION, FECHA_PAGO, VALOR_TOTAL_PAGO, COD_USUARIO)
    VALUES (V_COD_PAGO, SYSDATE, V_TOTAL, COD_USUARIO_P);

    FOR I IN 1 .. DETALLES_P.COUNT LOOP
        INSERT INTO JRGY_DETALLE_PAGO_HABITACION (COD_PAGO_HABITACION, COD_HABITACION, FECHA_ESTADIA, PRECIO_HABITACION, DIAS)
        VALUES (V_COD_PAGO, DETALLES_P(I).COD_HABITACION, DETALLES_P(I).FECHA_ESTADIA, DETALLES_P(I).PRECIO_HABITACION, DETALLES_P(I).DIAS);

        UPDATE JRGY_HABITACION
        SET COD_ESTADO_HABITACION = (
            SELECT COD_ESTADO_HABITACION
            FROM JRGY_CAT_ESTADO_HABITACION
            WHERE UPPER(ESTADO_HABITACION) = 'OCUPADA'
        )
        WHERE COD_HABITACION = DETALLES_P(I).COD_HABITACION;
    END LOOP;

    COD_PAGO_OUT := V_COD_PAGO;
    TOTAL_OUT := V_TOTAL;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Gestor: recalcular stock desde movimientos
CREATE OR REPLACE PROCEDURE JRGY_PRO_RECALC_STOCK (
    COD_PRODUCTO_P IN NUMBER
)
IS
    V_STOCK NUMBER := 0;
BEGIN
    SELECT NVL(SUM(CASE WHEN TIPO_MOVIMIENTO = 'ENTRADA' THEN CANTIDAD WHEN TIPO_MOVIMIENTO = 'SALIDA' THEN -CANTIDAD ELSE 0 END), 0)
    INTO V_STOCK
    FROM JRGY_MOVIMIENTO_STOCK
    WHERE COD_PRODUCTO = COD_PRODUCTO_P;

    UPDATE JRGY_PRODUCTO SET STOCK_PRODUCTO = V_STOCK WHERE COD_PRODUCTO = COD_PRODUCTO_P;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20044, 'PRODUCTO NO ENCONTRADO');
    END IF;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Gestor: asignar rol a usuario
CREATE OR REPLACE PROCEDURE JRGY_PRO_ASIGNAR_ROL (
    COD_USUARIO_P IN NUMBER,
    COD_ROL_P IN NUMBER
)
IS
    CURR SYS_REFCURSOR;
BEGIN
    CRUD_USUARIO_ROL('C', COD_USUARIO_P, COD_ROL_P, CURR);
END;
/

-- Reportes
CREATE OR REPLACE PACKAGE PKG_REPORTES AS
    TYPE CURSOR_P IS REF CURSOR;
    PROCEDURE REP_TOP_PRODUCTOS_MES (ANIO IN NUMBER, MES IN NUMBER, CURSOR_OUT OUT CURSOR_P);
    PROCEDURE REP_OCUPACION_HABITACIONES (CURSOR_OUT OUT CURSOR_P);
    PROCEDURE REP_COMPRAS_POR_PROVEEDOR (CURSOR_OUT OUT CURSOR_P);
END PKG_REPORTES;
/

CREATE OR REPLACE PACKAGE BODY PKG_REPORTES AS
    PROCEDURE REP_TOP_PRODUCTOS_MES (ANIO IN NUMBER, MES IN NUMBER, CURSOR_OUT OUT CURSOR_P) IS
    BEGIN
        OPEN CURSOR_OUT FOR
            SELECT dv.COD_PRODUCTO,
                   SUM(dv.CANTIDAD) AS TOTAL_VENDIDO,
                   SUM(dv.PRECIO_TOTAL) AS TOTAL_MONTO
            FROM JRGY_VENTA v
            JOIN JRGY_DETALLE_VENTA dv ON dv.COD_VENTA = v.COD_VENTA
            WHERE EXTRACT(YEAR FROM v.FECHA_VENTA) = ANIO
              AND EXTRACT(MONTH FROM v.FECHA_VENTA) = MES
            GROUP BY dv.COD_PRODUCTO
            ORDER BY TOTAL_VENDIDO DESC;
    END;

    PROCEDURE REP_OCUPACION_HABITACIONES (CURSOR_OUT OUT CURSOR_P) IS
    BEGIN
        OPEN CURSOR_OUT FOR
            SELECT CEH.ESTADO_HABITACION,
                   COUNT(*) AS TOTAL
            FROM JRGY_HABITACION H
            LEFT JOIN JRGY_CAT_ESTADO_HABITACION CEH ON CEH.COD_ESTADO_HABITACION = H.COD_ESTADO_HABITACION
            GROUP BY CEH.ESTADO_HABITACION;
    END;

    PROCEDURE REP_COMPRAS_POR_PROVEEDOR (CURSOR_OUT OUT CURSOR_P) IS
    BEGIN
        OPEN CURSOR_OUT FOR
            SELECT dp.COD_PROVEEDOR,
                   SUM(dp.PRECIO_TOTAL) AS TOTAL_COMPRADO,
                   COUNT(*) AS LINEAS
            FROM JRGY_DETALLE_PEDIDO dp
            GROUP BY dp.COD_PROVEEDOR
            ORDER BY TOTAL_COMPRADO DESC;
    END;
END PKG_REPORTES;
/

PROMPT Triggers de negocio...
-- 7) Triggers de negocio
CREATE OR REPLACE TRIGGER TRG_VALIDA_STOCK_VENTA
    BEFORE INSERT OR UPDATE ON JRGY_DETALLE_VENTA
    FOR EACH ROW
DECLARE
    V_STOCK NUMBER;
BEGIN
    SELECT NVL(STOCK_PRODUCTO,0) INTO V_STOCK FROM JRGY_PRODUCTO WHERE COD_PRODUCTO = :NEW.COD_PRODUCTO;
    IF :NEW.CANTIDAD > V_STOCK THEN
        RAISE_APPLICATION_ERROR(-20050, 'STOCK INSUFICIENTE PARA PRODUCTO ' || :NEW.COD_PRODUCTO);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_HAB_OCUPADA_ON_DETALLE
    AFTER INSERT ON JRGY_DETALLE_PAGO_HABITACION
    FOR EACH ROW
BEGIN
    UPDATE JRGY_HABITACION
    SET COD_ESTADO_HABITACION = (
        SELECT COD_ESTADO_HABITACION
        FROM JRGY_CAT_ESTADO_HABITACION
        WHERE UPPER(ESTADO_HABITACION) = 'OCUPADA'
    )
    WHERE COD_HABITACION = :NEW.COD_HABITACION;
END;
/

CREATE OR REPLACE TRIGGER TRG_HAB_LIBRE_ON_DETALLE_DEL
    AFTER DELETE ON JRGY_DETALLE_PAGO_HABITACION
    FOR EACH ROW
BEGIN
    UPDATE JRGY_HABITACION
    SET COD_ESTADO_HABITACION = (
        SELECT COD_ESTADO_HABITACION
        FROM JRGY_CAT_ESTADO_HABITACION
        WHERE UPPER(ESTADO_HABITACION) = 'LIBRE'
    )
    WHERE COD_HABITACION = :OLD.COD_HABITACION;
END;
/

PROMPT Datos iniciales (usuario admin semilla)...
DECLARE
    v_admin_role_id NUMBER;
    v_user_id NUMBER;
    v_estado_activo NUMBER;
    v_dummy NUMBER;
BEGIN
    -- Asegura estado ACTIVO en catálogo de estado de usuario.
    BEGIN
        SELECT COD_ESTADO_USUARIO INTO v_estado_activo
        FROM JRGY_CAT_ESTADO_USUARIO
        WHERE UPPER(ESTADO_USUARIO) = 'ACTIVO';
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_estado_activo := 1;
            INSERT INTO JRGY_CAT_ESTADO_USUARIO (COD_ESTADO_USUARIO, ESTADO_USUARIO)
            VALUES (v_estado_activo, 'ACTIVO');
    END;

    -- Obtiene el rol ADMIN (asumiendo que existe en JRGY_ROL).
    SELECT COD_ROL INTO v_admin_role_id FROM JRGY_ROL WHERE UPPER(NOMBRE_ROL) = 'ADMIN';

    -- Busca usuario por email; si no existe, lo crea.
    BEGIN
        SELECT COD_USUARIO INTO v_user_id FROM JRGY_USUARIO WHERE LOWER(EMAIL_USUARIO) = LOWER('gustavo.admin@example.com');
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO JRGY_USUARIO (
                NOMBRE_USUARIO,
                APELLIDO1_USUARIO,
                APELLIDO2_USUARIO,
                EMAIL_USUARIO,
                TELEFONO_USUARIO,
                CONTRASENA_HASH,
                COD_ESTADO_USUARIO
            ) VALUES (
                'Gustavo_admin_page',
                'Gallegos',
                'Harnisch',
                'gustavo.admin@example.com',
                123456789,
                '$2y$10$LpD0f3wJ8i0R5I72dq4KC.UEMlOqhgCXNEuWP9pFYVod4SElutUKC',
                v_estado_activo
            ) RETURNING COD_USUARIO INTO v_user_id;
    END;

    -- Asigna rol ADMIN si aún no lo tiene.
    BEGIN
        SELECT 1 INTO v_dummy FROM JRGY_USUARIO_ROL WHERE COD_USUARIO = v_user_id AND COD_ROL = v_admin_role_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO JRGY_USUARIO_ROL (COD_USUARIO, COD_ROL) VALUES (v_user_id, v_admin_role_id);
    END;
END;
/
