PROMPT Patch regiones/ciudades y CRUD proveedores con ciudad (usar despues de Base_de_datos.sql)

-- 1) Agrega COD_CIUDAD a proveedor y FK si no existen
DECLARE
    v_dummy NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_dummy FROM user_tab_cols WHERE table_name = 'JRGY_PROVEEDOR' AND column_name = 'COD_CIUDAD';
    IF v_dummy = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE JRGY_PROVEEDOR ADD COD_CIUDAD NUMBER';
    END IF;

    SELECT COUNT(*) INTO v_dummy FROM user_constraints WHERE constraint_name = 'FK_JRGY_PROVEEDOR_CIUDAD';
    IF v_dummy = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE JRGY_PROVEEDOR ADD CONSTRAINT FK_JRGY_PROVEEDOR_CIUDAD FOREIGN KEY (COD_CIUDAD) REFERENCES JRGY_CIUDAD (COD_CIUDAD)';
    END IF;
END;
/

-- 2) Secuencia + trigger PK proveedor (si no existen)
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_sequences WHERE sequence_name = 'SQ_PK_PROVEEDOR';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SQ_PK_PROVEEDOR START WITH 100 INCREMENT BY 1 NOMAXVALUE NOCYCLE';
    END IF;
    EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER TRG_PK_PROVEEDOR
        BEFORE INSERT ON JRGY_PROVEEDOR
        FOR EACH ROW
        BEGIN
            IF :NEW.COD_PROVEEDOR IS NULL THEN
                :NEW.COD_PROVEEDOR := SQ_PK_PROVEEDOR.NEXTVAL;
            END IF;
        END;';
END;
/

-- 3) Carga regiones y ciudades (sin acentos)
BEGIN
    MERGE INTO JRGY_REGION r USING (SELECT 10 AS id, 'MAULE' AS nombre FROM dual) d ON (r.COD_REGION=d.id)
    WHEN NOT MATCHED THEN INSERT (COD_REGION, REGION) VALUES (d.id, d.nombre);
    MERGE INTO JRGY_REGION r USING (SELECT 11 AS id, 'OHIGGINS' AS nombre FROM dual) d ON (r.COD_REGION=d.id)
    WHEN NOT MATCHED THEN INSERT (COD_REGION, REGION) VALUES (d.id, d.nombre);
    MERGE INTO JRGY_REGION r USING (SELECT 12 AS id, 'NUBLE' AS nombre FROM dual) d ON (r.COD_REGION=d.id)
    WHEN NOT MATCHED THEN INSERT (COD_REGION, REGION) VALUES (d.id, d.nombre);
    MERGE INTO JRGY_REGION r USING (SELECT 13 AS id, 'BIOBIO' AS nombre FROM dual) d ON (r.COD_REGION=d.id)
    WHEN NOT MATCHED THEN INSERT (COD_REGION, REGION) VALUES (d.id, d.nombre);
END;
/

BEGIN
    FOR rec IN (
        SELECT 100 AS id, 'TALCA' AS nombre, 10 AS region FROM dual UNION ALL
        SELECT 101, 'CURICO', 10 FROM dual UNION ALL
        SELECT 102, 'LINARES', 10 FROM dual UNION ALL
        SELECT 103, 'CAUQUENES', 10 FROM dual UNION ALL
        SELECT 110, 'RANCAGUA', 11 FROM dual UNION ALL
        SELECT 111, 'SAN FERNANDO', 11 FROM dual UNION ALL
        SELECT 120, 'CHILLAN', 12 FROM dual UNION ALL
        SELECT 121, 'SAN CARLOS', 12 FROM dual UNION ALL
        SELECT 130, 'CONCEPCION', 13 FROM dual UNION ALL
        SELECT 131, 'LOS ANGELES', 13 FROM dual
    ) LOOP
        MERGE INTO JRGY_CIUDAD c USING (SELECT rec.id id, rec.nombre nombre, rec.region region FROM dual) d
        ON (c.COD_CIUDAD = d.id)
        WHEN NOT MATCHED THEN
            INSERT (COD_CIUDAD, CIUDAD, COD_REGION) VALUES (d.id, d.nombre, d.region);
    END LOOP;
    COMMIT;
END;
/

-- 4) Recreate procedures de proveedor (incluye ciudad y nombres de region/ciudad)
CREATE OR REPLACE PROCEDURE JRGY_PRO_PROVEEDOR_LISTAR(
    CUR OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN CUR FOR
        SELECT p.COD_PROVEEDOR,
               p.NOMBRE_PROVEEDOR,
               p.DIRECCION_PROVEEDOR,
               p.TELEFONO_PROVEEDOR,
               p.COD_REGION,
               p.COD_CIUDAD,
               r.REGION AS REGION_NOMBRE,
               c.CIUDAD AS CIUDAD_NOMBRE
        FROM JRGY_PROVEEDOR p
        LEFT JOIN JRGY_REGION r ON r.COD_REGION = p.COD_REGION
        LEFT JOIN JRGY_CIUDAD c ON c.COD_CIUDAD = p.COD_CIUDAD
        ORDER BY p.NOMBRE_PROVEEDOR;
END;
/

CREATE OR REPLACE PROCEDURE JRGY_PRO_PROVEEDOR_CREAR(
    P_NOMBRE IN VARCHAR2,
    P_DIRECCION IN VARCHAR2,
    P_TELEFONO IN NUMBER,
    P_REGION IN NUMBER,
    P_CIUDAD IN NUMBER,
    P_ID OUT NUMBER
)
IS
BEGIN
    INSERT INTO JRGY_PROVEEDOR (COD_PROVEEDOR, NOMBRE_PROVEEDOR, DIRECCION_PROVEEDOR, TELEFONO_PROVEEDOR, COD_REGION, COD_CIUDAD)
    VALUES (SQ_PK_PROVEEDOR.NEXTVAL, P_NOMBRE, P_DIRECCION, P_TELEFONO, P_REGION, P_CIUDAD)
    RETURNING COD_PROVEEDOR INTO P_ID;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE JRGY_PRO_PROVEEDOR_ACTUALIZAR(
    P_ID IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_DIRECCION IN VARCHAR2,
    P_TELEFONO IN NUMBER,
    P_REGION IN NUMBER,
    P_CIUDAD IN NUMBER
)
IS
BEGIN
    UPDATE JRGY_PROVEEDOR
    SET NOMBRE_PROVEEDOR = P_NOMBRE,
        DIRECCION_PROVEEDOR = P_DIRECCION,
        TELEFONO_PROVEEDOR = P_TELEFONO,
        COD_REGION = P_REGION,
        COD_CIUDAD = P_CIUDAD
    WHERE COD_PROVEEDOR = P_ID;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20026, 'PROVEEDOR NO ENCONTRADO');
    END IF;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE JRGY_PRO_PROVEEDOR_BORRAR(
    P_ID IN NUMBER
)
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM JRGY_DETALLE_PEDIDO WHERE COD_PROVEEDOR = P_ID;
    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20104, 'NO SE PUEDE ELIMINAR: TIENE PEDIDOS');
    END IF;

    DELETE FROM JRGY_PROVEEDOR WHERE COD_PROVEEDOR = P_ID;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20026, 'PROVEEDOR NO ENCONTRADO');
    END IF;
    COMMIT;
END;
/
